events { worker_connections 1024; }

http {
 log_format detailed '$remote_addr -> $host "$request" XFF_in="$http_x_forwarded_for"';
 access_log /dev/stdout detailed;
 error_log  /dev/stderr warn;

 server {
     listen 80;
     server_name _;
      location /direct {
         proxy_set_header X-Forwarded-For "$remote_addr, 172.28.10.13";
         proxy_set_header X-Real-IP       $remote_addr;
         proxy_set_header Host            $host;
         proxy_pass http://app:80/get;
     }
      location /from-upstream {
         proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for,  172.28.10.13" ;
         proxy_set_header X-Real-IP       $http_x_real_ip;
         proxy_set_header Host            $host;
         proxy_pass http://app:80/get;
     }
 }
}

